#!/bin/bash

# This file is needed to make the binder demonstrations work
# because we use a pyproject.toml file, Binder won't build
# the environment unless we manually specify it here

set -e
# Work-around until pip stops making this broken in requirement.txt
pip install -e .[molecules]