name: astartes
channels:
  - defaults
dependencies:
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - libcxx=14.0.6
  - libffi=3.4.2
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=22.3.1
  - python=3.8.11
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.40.1
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
    - aimsim==2.0.1
    - anyio==3.6.2
    - appnope==0.1.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - astartes==0.0.0
    - astroid==2.14.2
    - asttokens==2.2.1
    - attrs==22.2.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.2
    - bleach==6.0.0
    - cffi==1.15.1
    - comm==0.1.2
    - contourpy==1.0.7
    - customtkinter==4.6.3
    - cycler==0.11.0
    - darkdetect==0.8.0
    - debugpy==1.6.6
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.6
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - fonttools==4.38.0
    - fqdn==1.5.1
    - idna==3.4
    - importlib-metadata==6.0.0
    - importlib-resources==5.10.2
    - ipykernel==6.21.2
    - ipython==8.10.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - isort==5.12.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==8.0.2
    - jupyter-console==6.5.1
    - jupyter-core==5.2.0
    - jupyter-events==0.6.3
    - jupyter-server==2.2.1
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.5
    - kennard-stone==1.1.2
    - kiwisolver==1.4.4
    - lazy-object-proxy==1.9.0
    - markupsafe==2.1.2
    - matplotlib==3.7.0
    - matplotlib-inline==0.1.6
    - mccabe==0.7.0
    - mistune==2.0.5
    - multiprocess==0.70.14
    - nbclassic==0.5.1
    - nbclient==0.7.2
    - nbconvert==7.2.9
    - nbformat==5.7.3
    - nest-asyncio==1.5.6
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numpy==1.24.2
    - packaging==23.0
    - padelpy==0.1.13
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.4.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.0.0
    - plotly==5.13.0
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.36
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.14.0
    - pylint==2.16.2
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-json-logger==2.0.6
    - pytz==2022.7.1
    - pyyaml==5.4.1
    - pyzmq==25.0.0
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - rdkit==2022.9.4
    - rdkit-pypi==2022.9.4
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - scikit-learn==1.2.1
    - scikit-learn-extra==0.2.0
    - scipy==1.10.0
    - seaborn==0.12.2
    - send2trash==1.8.0
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.4
    - stack-data==0.6.2
    - tabulate==0.9.0
    - tenacity==8.2.1
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tkinter-tooltip==2.1.0
    - tomli==2.0.1
    - tomlkit==0.11.6
    - tornado==6.2
    - traitlets==5.9.0
    - typing-extensions==4.5.0
    - uri-template==1.2.0
    - wcwidth==0.2.6
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - widgetsnbextension==4.0.5
    - wrapt==1.14.1
    - zipp==3.13.0