name: Ensure Code Formatting
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64
      - name: Install Dependencies
        run: |
          python -m pip install pycodestyle autopep8 isort
          python -m pip install -e .
      
      - name: Check Code Formatting Errors
        run: |
          pycodestyle --statistics --count --max-line-length=150 --show-source --ignore=E203 .

      - name: Check Import Ordering Errors
        run: |
          isort --check-only --verbose .